trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: npm install
  displayName: npm install
- script: npm test
  displayName: test
- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'Swaggger Tools ESRP connection'
    FolderPath: 'src/dotnet/AutoRest/bin/netcoreapp2.0'
    Pattern: '*.dll,*.exe'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
          {
              "KeyCode": "CP-230012",
              "OperationSetCode": "SigntoolSign",
              "parameters": [
                  {
                      "parameterName": "OpusName",
                      "parameterValue": "Microsoft"
                  },
                  {
                      "parameterName": "OpusInfo",
                      "parameterValue": "http://www.microsoft.com"
                  },
                  {
                      "parameterName": "PageHash",
                      "parameterValue": "/NPH"
                  },
                  {
                      "parameterName": "FileDigest",
                      "parameterValue": "/fd sha256"
                  },
                  {
                      "parameterName": "TimeStamp",
                      "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                  }
              ],
              "ToolName": "signtool.exe",
              "ToolVersion": "6.2.9304.0"
          }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- script: npm pack
  displayName: pack
- task: CopyFiles@2
  displayName: 'Copy Files to: drop'
  inputs:
    Contents: '*.tgz'
    TargetFolder: drop
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.SourcesDirectory)/drop

- task: CredScan@2
  inputs:
    toolMajorVersion: 'V2'

- task: PostAnalysis@1
  inputs:
    AllTools: false
    APIScan: false
    BinSkim: false
    CodesignValidation: false
    CredScan: true
    FortifySCA: false
    FxCop: false
    ModernCop: false
    PoliCheck: false
    RoslynAnalyzers: false
    SDLNativeRules: false
    Semmle: false
    TSLint: false
    ToolLogsNotFoundAction: 'Standard'


